

server:
  port: 9090

debug: false


# 配置spring-logging 原生默认日志
logging:
#  level: info
  file:
    clean-history-on-start: true
    path: log
    name: mylog.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl