server:
  port: 8088

# 白名单用户
kimking:
  whitelist:
    users: aaa,111,xiaofuge

# 自定义的配置有大小写的属性时会转换为中横线
mybatis:
  datasource:
    enable: true
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bugstack?useUnicode=true
    username: root
    password: 123456
    mapper-locations: classpath*:mapper/*.xml
    base-dao-package: priv.kimking.base.spring.mybatis.infrastructure.dao
